### ISSUE TITLE
source configuration. not working. can't enable for CameraSource.Camera / CameraSource.Photos

### ISSUE THREAD

**Issue by aacassandra** [ionic-team/pwa-elements#83] opened 2021-05-12 12:52 UTC
Hello friend. thanks for this plugin. maybe im found the problem
im using:
"@ionic/pwa-elements": "^3.0.2",
ionic vue 
"@capacitor/core": "2.4.5",

Im using this plugin for my pwa apps. i want this plugin with only source.camera not source.prompt, but im still getting source.prompt. I've also tried source.photos but it still generates source.prompt. I do not know. is this a bug am i something wrong. please help my friend. Thank you in advance.

the rotate button also doesn't work on the web pwa. for mobile, I don't know, because I haven't tested it and there is no interest there

this my code
```
import { Plugins, CameraResultType, CameraSource } from '@capacitor/core';
...
Camera.getPhoto({
    quality: 100,
    source: CameraSource.Camera,
    resultType: CameraResultType.Base64
}).then((res) => {
    console.log(res)
})
```

i have reproduced this issue in this repo, you can clone this repo and run this after cloning
```npm install && npm run serve```
look src/components/ExplorerContainer.vue
https://github.com/aacassandra/ionic-vue-camera-testing

<img width="346" alt="Screenshot 2021-05-12 at 19 40 28" src="https://user-images.githubusercontent.com/29236058/117976477-078c5d00-b35a-11eb-8824-be7f5aedb794.png">

sorry about my bad english

**Comment by glennvdw** [comment] 2021-05-17 07:44
I'm facing the same issue.

The problem is here: https://github.com/ionic-team/pwa-elements/blob/6e1394a00b891a0242fea1f41b151681f1012d2a/src/components/camera/camera.tsx#L462

There is no conditional for showing the `<div class="pick-image">`.

**Comment by aacassandra** [comment] 2021-05-17 17:16
hmm. there doesn't seem to be a solution at this point

**Comment by jcesarmobile** [comment] 2021-06-23 10:58
the screenshot is showing the camera, that's how the camera looks like.

in fact prompt doesn't work yet, will work soon after https://github.com/ionic-team/capacitor-plugins/pull/487 gets merged

**Closed by jcesarmobile** 2021-06-23 10:58 UTC
