### ISSUE TITLE
Camera: Uncaught (in promise) TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by BluebambooSRL** [ionic-team/pwa-elements#66] opened 2020-10-23 21:58 UTC
npm list @stencil/core
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

ERROR
pwa-camera.entry.js:292 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at CameraPWA.initPhotoCapabilities (pwa-camera.entry.js:292)
    at async CameraPWA.initStream (pwa-camera.entry.js:281)

**Expected behavior:**

**Steps to reproduce:**
I follow the development code on https://ionicframework.com/docs/angular/your-first-app/2-taking-photos

Ionic:

   Ionic CLI                     : 6.12.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.1
   @angular-devkit/build-angular : 0.1002.0
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.2.0
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : 0.15.1
   native-run  : 1.2.2

System:

   NodeJS : v12.16.0 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina

**Comment by lleaonet** [comment] 2020-10-24 12:31
I have the same error here! Any solution or workaround?

**Comment by Alexookah** [comment] 2020-10-26 11:24
same error as well

**Comment by xErik** [comment] 2020-10-27 09:13
same error, following

**Comment by pmolinal** [comment] 2020-10-27 13:22
i have the same error..

Ionic:

   Ionic CLI                     : 6.10.1 (C:\Users\patricio\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.5
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : 0.11.0
   native-run  : 0.3.0

System:

   NodeJS : v12.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10

**Comment by rufdev** [comment] 2020-10-28 22:17
yep

**Comment by m4g1c14n2000** [comment] 2020-10-29 13:05
Same problem, please help

**Comment by Lenoxy** [comment] 2020-11-02 10:15
Same error, help would be appreciated

**Comment by jj-whitehead** [comment] 2020-11-02 12:06
Same error here..

**Comment by L96Github** [comment] 2020-11-03 09:44
Same, no news on this?

**Comment by patrick-pol** [comment] 2020-11-05 16:03
Same error here

**Comment by sergidb** [comment] 2020-11-06 20:08
Same error

**Comment by smrtnrd** [comment] 2020-11-08 22:17
Same error too.

**Comment by MaximePoitoux** [comment] 2020-11-09 10:50
Same error, a charitable soul to help us?

**Comment by abhidynmc** [comment] 2020-11-10 10:38
Same Error

**Comment by shadowboxingskills** [comment] 2020-11-11 15:48
+1

**Comment by mtsmachado8** [comment] 2020-11-16 18:42
Duplicate of: https://github.com/ionic-team/pwa-elements/issues/67
i solved it, look there please.
More news on that soon

**Comment by theproducer** [comment] 2020-12-11 17:47
The PR for this fix is now in 3.0.2

**Closed** 2020-12-11 17:47 UTC
